# Generated by Django 3.0.2 on 2020-01-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('image_url', models.URLField()),
                ('long_description', models.CharField(max_length=500)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
    ]
